# Generated by Django 5.2.1 on 2025-06-02 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('unica', 'Única'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='unica', max_length=10)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
