# Generated by Django 5.2.1 on 2025-06-03 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('unica', 'Única'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='unica', max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
