# Generated by Django 5.2.1 on 2025-06-03 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('feito', 'Feito'), ('abortado', 'Abortado')], default='pendente', max_length=10)),
                ('recurrence', models.CharField(choices=[('unico', 'Único'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='unico', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
