# Generated by Django 5.2.1 on 2025-06-01 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('feito', 'Feito'), ('abortado', 'Abortado')], default='pendente', max_length=10)),
                ('recurrence', models.CharField(choices=[('unico', 'Único'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='unico', max_length=10)),
            ],
        ),
    ]
