# Generated by Django 5.2.1 on 2025-06-02 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('learned', models.TextField(blank=True, null=True)),
                ('improved', models.TextField(blank=True, null=True)),
                ('failed', models.TextField(blank=True, null=True)),
                ('feeling', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
